### ISSUE TITLE
Check for missing containers failing, no planemo shed_lint -s option

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-iuc#5500]
I'm tracing a CI failure on https://github.com/peterjc/galaxy_blast/ after recently updating to the tools-iuc GitHub Actions, under "Check for missing containers (3.7)". It turns out the IUC repo is also failing here (cross reference #5499):

```
planemo shed_lint --tools --ensure_metadata --urls --report_level all --fail_level error --recursive tools/blast_rbh --biocontainers -s tests,output,inputs,help,general,command,citations,tool_xsd
Usage: planemo shed_lint [OPTIONS] PROJECT
Try 'planemo shed_lint --help' for help.

Error: No such option: -s
```

That is coming from here the ``ci.yaml`` block added in pull request #5242:

```
    - name: Planemo lint
      uses: galaxyproject/planemo-ci-action@v1
      id: lint
      with:
        mode: lint
        repository-list: ${{ needs.setup.outputs.repository-list }}
        tool-list: ${{ needs.setup.outputs.tool-list }}
        additional-planemo-options: --biocontainers -s tests,output,inputs,help,general,command,citations,tool_xsd
```

My local copy of planemo 0.75.12 does indeed lack a documented ``-s`` switch, and I don't see any evidence of this existing in the source code here:

https://github.com/galaxyproject/planemo/blob/master/planemo/commands/cmd_shed_lint.py

Was this a typo for ``-r`` (recursive)?
