### ISSUE TITLE
Missing dependency on abyss

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/tools-iuc#674]
The abyss package depends also on `bsdmainutils` (ubuntu package here).
If you look at `abyss-tabtomd`, you will see that it refers the binary `column`.

Most probably on 99% of installations this is silent, but that is not the case on average docker containers

**Comment by bgruening** [comment]
@tiagoantao are you referring to the galaxy package or conda package?

**Comment by tiagoantao** [comment]
@bgruening Did not test the conda package yet. This is actually inside your docker machine after I install  abyss.
I had to do apt-get install bsdmainutils .
But I do not believe this is a problem with your container, but a dependency that should be specified here...

**Comment by bgruening** [comment]
Ok, thanks for reporting!

**Comment by nsoranzo** [comment]
`column` under Fedora/RedHat/CentOS is provided by `util-linux` RPM (`util-linux-ng` in older versions), which is a fundamental package. It seems that in Debian/Ubuntu, `column` is indeed part of `bsdmainutils`, which is not fundamental.

`abyss-tabtomd` also uses `awk`. Do you use `abyss-tabtomd` in a wrapper? If not, I'm not sure it makes sense to create a `util-linux` package and add 2 dependencies.

**Comment by tiagoantao** [comment]
@nsoranzo I have installed the iuc version of the abyss tool inside @bgruening docker image.

**Comment by nsoranzo** [comment]
@tiagoantao And what happened? Any error or log?

**Comment by bgruening** [comment]
ping @tiagoantao

**Comment by tiagoantao** [comment]
Sorry for the long delay. Personal issues...

```
/galaxy-central/tool_deps/abyss/1.9.0/iuc/package_abyss_1_9_0/ded58f1da91c/bin/abyss-tabtomd: 12: /galaxy-central/tool_deps/abyss/1.9.0/iuc/package_abyss_1_9_0/ded58f1da91c/bin/abyss-tabtomd: column: not found
make: *** [abyss-stats.md] Error 127
make: *** Deleting file `abyss-stats.md'
```

**Comment by tiagoantao** [comment]
One more: abyss also depends on bwa...

**Comment by tiagoantao** [comment]
```
Consider increasing the coverage threshold parameter, c, to 3.85106.
/bin/bash: bwa: command not found
make: *** [abyss-8.fa.bwt] Error 127
```

**Comment by nsoranzo** [comment]
@tiagoantao Thanks for details! I've added bwa (and pandoc for v. 2.0.1) to the runtime requirements of the `abyss` Bioconda package in https://github.com/bioconda/bioconda-recipes/pull/2511. I've also prepared a PR to update the ABySS tool wrapper to use v. 2.0.1 from Conda-only, dropping tool_dependencies and adding a test for scaffolding with long sequences (where BWA is used). Sounds good for you?

**Comment by nsoranzo** [comment]
Forgot to say: I have no plan to add a requirement for `column`, it's a basic binary which should be on every system, IMHO it's a bug in Debian/Ubuntu if it's not, since it is part of `util-linux` upstream. If someone creates an util-linux package in conda-forge, I can add a dependency on that to the `abyss` bioconda package.

**Comment by tiagoantao** [comment]
Thanks, this is amazing.
With regards to `column`, this is mostly a docker problem, As docker containers are slim this might be missing and it is actually missing on the version that I am using from Björn (from ~6 months ago). ping @bgruening

**Comment by bgruening** [comment]
@tiagoantao you are using the mulled Docker container? Awesome!
But yes this one is really slim and we need the `column` binary, it is a dependency and need to be defined. We do not make a lot of assumption on the runtime environment :)

**Comment by tiagoantao** [comment]
Around here I have a 100% docker infrastructure and I use your container with minor modifications (external database container, LDAP)
I can just update the local dockerfile, that is fine by me. But you might want to think about a case like this. I personally have no preference myself... Just tell me your preferred policy and I will follow here.

**Comment by bgruening** [comment]
Wow, nice to know that our stuff is useful for someone! 
I would prefer a package for this not only for me, but because it is the `right` thing to do. What ever will come next after Docker/Conda to have a detailed list of dependencies will help the entire bioinf community.

Off topic: Do you have a postgresql container communication with compose to docker-stable?

**Comment by tiagoantao** [comment]
No not using compose. I currently have (mostly up to date, but not totally) the infrastructure available on http://virtual-core.tiago.org/

This is a set of docker containers with everything included (LDAP, Postgres, SSH server, software installation, Jupyter, ...).

Also:
https://github.com/tiagoantao/virtual-core

**Comment by nsoranzo** [comment]
@bgruening So, can you create a conda-forge package containing `column`? There are 2 similar version: one in [util-linux](https://git.kernel.org/cgit/utils/util-linux/util-linux.git/), the other in [bsdmainutils](https://anonscm.debian.org/gitweb/?p=bsdmainutils/bsdmainutils.git). Plus macOS has another BSD-derived version in `/usr/bin/column` ...
I think that creating a proper package for `util-linux` (there's one in the default channel, but it has no binaries) is the best option.

**Comment by bgruening** [comment]
This is not as easy as it seems.
I have this so far:
```
{% set name = "util-linux" %}
{% set version = "2.28.2" %}
{% set sha256 = "7e0cd6772f68561253d5ccae3c4ae4703bad938a6a324e47ddc4c342ab73f8f8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.kernel.org/pub/linux/utils/util-linux/v2.28/util-linux-2.28.2.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: ./configure --help && ./configure --prefix=$PREFIX --without-python --enable-column && make column && mv column $PREFIX/bin/

requirements:
  build:
    - ncurses
    - readline
    - python
  run:

test:
  # Some package might need a `test/commands` key to check CLI.
  commands:
    - echo "foo bar baz" | column -t

about:
  home: https://git.kernel.org/cgit/utils/util-linux/util-linux.git/about/
  license: GPL
  summary: 'util-linux is a random collection of Linux utilities'
  dev_url: git://git.kernel.org/pub/scm/utils/util-linux/util-linux.git

extra:
  recipe-maintainers:
    - bgruening
```

@nsoranzo can you come up with a list of tools that are needed from this package? Compiling all the fsck tools etc is complicated, so I prefer a whitelist :)
